apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: exo
  namespace: exo
  labels:
    app: exo
spec:
  selector:
    matchLabels:
      app: exo
  template:
    metadata:
      labels:
        app: exo
    spec:
      initContainers:
        - name: init-permissions
          image: busybox:1.36
          command:
            - sh
            - -c
            - >
              mkdir -p /home/exo/.cache/exo &&
              chown -R 10001:10001 /data /home/exo/.cache/exo
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: exo-data
              mountPath: /data
            - name: exo-cache
              mountPath: /home/exo/.cache/exo
      terminationGracePeriodSeconds: 10
      containers:
        - name: exo
          image: ghcr.io/ianrelecker/exo:cpu
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 52415
          env:
            - name: EXO_HOME
              value: /data
            - name: CLANG
              value: "1"
          volumeMounts:
            - name: exo-data
              mountPath: /data
            - name: exo-cache
              mountPath: /home/exo/.cache/exo
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 10001
      volumes:
        - name: exo-data
          hostPath:
            path: /var/lib/exo-data
            type: DirectoryOrCreate
        - name: exo-cache
          hostPath:
            path: /var/lib/exo-cache
            type: DirectoryOrCreate
