apiVersion: v1
kind: Service
metadata:
  name: exo
  namespace: exo
  labels:
    app: exo
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: exo
  ports:
    - name: http
      port: 52415
      targetPort: 52415
